CLIENT_ID = 'R5KIOQJIXBTMSGBL0D3T3UCTJSMHLM5JWK15ZXEVRABUHMT1'  # your Foursquare ID
CLIENT_SECRET = 'V0PEZI5UQCNYEZH4COTUAWSR3JF0VYCQIEAUEIGQTKO4IBSX'  # your Foursquare Secret
ACCESS_TOKEN = 'SMJUGJNHW0X1COKCD3I0JBUKTPJUHRFBP0DE4VALKMAMRS20'
VERSION = '20180605'  # Foursquare API version
LIMIT = 100  # A default Foursquare API limit value
# https://www.google.com/?code=CJQFOCEV5OYSVVHREUFJ2N3CLXOZO3AEK5SFRNO4KTEG5TMK#_=_
# https://foursquare.com/oauth2/access_token?client_id=R5KIOQJIXBTMSGBL0D3T3UCTJSMHLM5JWK15ZXEVRABUHMT1&client_secret=V0PEZI5UQCNYEZH4COTUAWSR3JF0VYCQIEAUEIGQTKO4IBSX&grant_type=authorization_code&redirect_uri=https://www.google.com&code=CJQFOCEV5OYSVVHREUFJ2N3CLXOZO3AEK5SFRNO4KTEG5TMK#_=_
